### PR TITLE
Add repository module

### PR DESCRIPTION
**Pull request by matthiasbeyer**
This is the tracking-PR for the library implementation.

I would model this as extension to the `git2::Repository` type. Further, I would model each shell script into one function on `Repository`.

I would like to hear your opinion before digging further into this.

### CODE REVIEW

**Comment by matthiasbeyer** [comment]
Ah, and another thing: Do we want this to be GPL? I would say no, as this is a library others might want to use. As far as I know, LGPL does not work with Rust, as things are statically linked - so the best option would be MPL IMHO.

**Comment by Profpatsch** [comment]
> I would say no, as this is a library others might want to use.

Isn’t that what GPL is for?

**Comment by neithernut** [comment]
GPL prevents using a library in binaries licensed under more permissive licenses, like MIT and BSD. With rust, this issue is even more present, as the linking exception granted e.g. by LGPL doesn't apply, as there is not really a difference between implementation and interface (regarding the build process).

**Comment by Profpatsch** [comment]
> GPL prevents using a library in binaries licensed under more permissive licenses, like MIT and BSD.

Which is a feature imo. Of course, that’s for you to decide.

**Comment by neithernut** [comment]
> I would model this as extension to the `git2::Repository` type.

Yep. I'd have done the same thing.

> Further, I would model each shell script into one function on Repository.

With C++, I'd prefer private free functions. But with rust this seems to be a reasonable approach.

----

> > GPL prevents using a library in binaries licensed under more permissive licenses, like MIT and BSD.
>
> Which is a feature imo. Of course, that’s for you to decide.

It's an anti-feature in my opinion. Libraries are there to be used, especially those providing infrastructure. I would rather have devs working on non-free products use a library that's open source than have them build hafl-assed, broken crap.

If they don't want to contribute, have their own, private development and one day realize they have lost the possibility to incorporate upstream fixes and features in their products, that's not my problem.

**Comment by matthiasbeyer** [comment]
And this is wäre MPL steps in, afaik. With MPL you can use the library as you please, butbif you change it you have to contribute back.

So it's LGPL for Rust, essentially.

Either way, obligatorily: IANAL!

**Comment by neithernut** [comment]
I assuming that you are referring to the Mozilla Public License (not the Microsoft Public License). I would accept releasing the library under MPL2.0.

**Pull request merged**
