### PR TITLE
Clean imports

### PR DESCRIPTION
**Pull request by neithernut**
In some places, we import a specific data structure and use it in only one or two places. This PR targets those imports. Suggestions are welcome.

### CODE REVIEW

**Comment by neithernut** [comment]
So you'd rather have every single little type explicitly imported, resulting in a potentially obnoxiously humongous list of `foo::bar::{this, and, that, as, well, as, those, things}`?

**Comment by matthiasbeyer** [comment]
Yes. That's what it is for.

**Comment by neithernut** [comment]
Well, I have a _very_ different stance on that.

**Comment by neithernut** [comment]
Rebased due to merge conflicts.

**Comment by neithernut** [comment]
@matthiasbeyer please give an ACK/NACK on those changes. I'm willing to omit some of them if you feel that way, but some of them just make sense.

Regarding the changes in the logger module, another possibility would be to import `log::*`, since we are implementing a logger anyway.

**Comment by matthiasbeyer** [comment]
> Regarding the changes in the logger module, another possibility would be to import log::*, since we are implementing a logger anyway.

I'm generally against importing `*`, so I'm fine with this part. I'm also fine with the minifications or imports and the removal of the unused things.

Not with the "Importing modules and using the module::type path" part, as said above.

**Pull request merged**
