### PR TITLE
Remove WrappedGitError and replace with explicit error kinds

### PR DESCRIPTION
**Pull request by matthiasbeyer**

### CODE REVIEW

**Comment by neithernut** [comment]
Blocks #97.

**Comment by matthiasbeyer** [comment]
No time to finally solve this, feel free to fix up on your own.

**Comment by neithernut** [comment]
Ok, I'll look into it over the weekend.

**Comment by neithernut** [comment]
You used the error kinds of the library in the binary.

**Comment by neithernut** [comment]
You generally mix up the error types from the library with the one from the binary. For example nowhere in the library do we open a repo and yet you introduce a `CannotOpenRepository` error kind.

**Comment by matthiasbeyer** [comment]
You see that the few days vacation was overdue! :smile:

**Comment by matthiasbeyer** [comment]
I finally found time to fix this up.

If you are okay with this I would squash everything into one commit in this PR.

**Comment by matthiasbeyer** [comment]
Here we go. I hope you like the commit message.

**Pull request merged**
