### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by matthiasbeyer**
All changes tested with `cargo check`, the `log` update tested by executing (after all patches applied).

Because of #159 "log" might not be properly tested.

### CODE REVIEW

**Comment by matthiasbeyer** [comment]
The lib actually does not need `log`.

**Comment by matthiasbeyer** [comment]
Ping.

**Comment by neithernut** [comment]
Could you rebase this branch?

**Comment by matthiasbeyer** [comment]
Rebased and also updated `git2` to `0.7`. Lets see whether this still compiles with the new version of `git2`.

**Comment by neithernut** [comment]
Nope, but the issue may be resolved easily.

**Comment by matthiasbeyer** [comment]
I'm having a meetup now. We need to pass [this](https://docs.rs/git2/0.7.1/git2/struct.Sort.html) instead of the constants from 0.6, which vanished in 0.7.

**Comment by neithernut** [comment]
I already prepared some fixes. You should get them soon.

**Pull request merged**
