### PR TITLE
Do not call pager if we are printing to a pipe

### PR DESCRIPTION
**Pull request by matthiasbeyer**
Rel #161

### CODE REVIEW

**Comment by neithernut** [comment]
Did you actually test whether git doesn't already do the right thing here?

**Comment by matthiasbeyer** [comment]
Yes, I tested it and it broke. But funnily enough, I can not reproduce this issue right now (neither with `git dit` and the `git-dit` binary in `$PATH` nor with calling `git-dit` directly). Would not merge until further investigation.

**Comment by neithernut** [comment]
I just did a quick test with a shell-script which I named `git-printenv` in order to make it a subcommand:

```
#!/bin/sh

echo $GIT_EDITOR
echo $GIT_PAGER
git config core.editor
git config core.pager
echo $EDITOR
echo $PAGER
```

It appears that `git` does indeed not alter the environment variables or the configuration for non-interactive shells (tested by piping the output to `cat`). Hence, we should detect non-interactive shells. However, I would not do this at the call-site but rather handle it inside `programs.rs`. E.g. return a handle for accepting the input, which is either stdout or a pipe. Or unconditionally try to run `cat`.

**Comment by neithernut** [comment]
The issue was resolved by #180.

**Pull request closed without merging**
